channels:
  - bioconda
  - conda-forge
  - r
dependencies:
  - snakemake-minimal =5.7.0
  - fastqc =0.11.8
  - multiqc =1.7
  - trimmomatic =0.38
  - star =2.7.3a
  - samtools =1.9
  - subread =1.6.4
  - orthofinder =2.3.11
  - pandas =1.0.1
  - diamond
  - kallisto
  - bioconductor-genomicfeatures
  - bioconductor-rhdf5 
  - r-readr
  - bioconductor-tximport
  - bioconductor-deseq2
