#add channels

#add orthofinder stuff

kallisto
trimmomatic (pigz)
fastqc
multiqc

R packages
conda install -c bioconda bioconductor-genomicfeatures
conda install -c bioconda bioconductor-rhdf5 
conda install -c conda-forge r-readr
conda install -c bioconda bioconductor-tximport
conda install -c bioconda bioconductor-deseq2
