channels:
  - bioconda
  - conda-forge
  - r
  - anaconda
dependencies:
  - snakemake=5.20.1
  - fastqc =0.11.8
  - multiqc =1.7
  - trimmomatic =0.38
  - star =2.7.3a
  - samtools =1.9
  - subread =1.6.4
  - orthofinder =2.3.11
  - muscle
  - pandas =1.0.1
  - diamond
  - gmp
  - kallisto
  - bioconductor-genomicfeatures
  - bioconductor-rhdf5 
  - r-readr
  - bioconductor-tximport
  - bioconductor-deseq2
  - r-dplyr
  - r-stringr
  - ucsc-fasomerecords
