#### define options of your individual rules here: #####
### number of maximum threads for each run of sample during a specfifc rule: ###
### for fastqc the thread usage is set to 4 - IMO best in most cases ###

threads_kallisto_quant: 6
threads_star_index: 8
threads_trimmomatic: 6
threads_star: 6
#threads_samtools_markdup: 4
threads_index_sorted_bams_with_dups: 4
threads_index_sorted_bams_without_dups: 4
threads_featureCounts: 2


### Trimmomatic
#not yet implemented
trim_illuminaclip: "ILLUMINACLIP:adapters.fa:2:30:10"
#trim_illuminaclip: ""
trim_options: "SLIDINGWINDOW:4:20 MINLEN:40"


### STAR
## default parameters change these to your specific needs

##change STAR's --sjdbOverhang option; ideal value here is read_length-1
##e.g.: 2x100b paired-end reads, the ideal value is 100-1=99; varying length? then, do this with the max length
limitGenomeGenerateRAM: 60000000000
read_length_star_index: 99


## parameters when running usual pipeline ##
## option --genomeLoad NoShared memory will load into memory the whole index on each mapping run and delete it after the mapping ##
## with big genomes this is VERY memory intensive! e.g. the index for barley is ~ 40 Gb - so keep this in mind when setting the amount of paralelisation ##
## for example with 24 cores specified and a 6 threads per STAR align job: 24/6 = 4; 4 x 40 Gb ~ around 160  Gb of memory required! ##
## you can change the --genomeLoad parameter to other options e.g. keeping in memory one index for all mappings - however this can't be used in conjunction with 2-PASS mapping ##
## also removal of the index from memory would require an additional rule or manual removal via ipcs/ipcrm after everything is finished -- might change this in the future.. ## 
STAR: >
    --genomeLoad NoSharedMemory
    --outSAMtype BAM SortedByCoordinate
    --outSAMattributes NH   HI   AS   nM   NM   MD   jM   jI   XS
    --outSJfilterOverhangMin 30 12 12 12
    --outFilterMultimapNmax 1
    --outFilterScoreMin 0
    --outFilterMatchNminOverLread 0.66
    --outFilterMismatchNmax 10
    --outFilterMismatchNoverLmax 0.3
    --alignIntronMin 21
    --alignIntronMax 0
    --alignMatesGapMax 0
    --alignSJoverhangMin 5
    --alignSJDBoverhangMin 3
    --alignSoftClipAtReferenceEnds Yes
    --chimSegmentMin 0
    --chimScoreMin 0
    --chimScoreSeparation 10
    --chimJunctionOverhangMin 20
    --outFilterMultimapScoreRange 0


## try automatic filtering for longest isoform of fastas?
## -> relatively stable for standard fasta files from e.g. Ensembl
## when not set to "YES", we assume you performed appropiate filtering yourself or specifically want all isoforms
auto_isoform_filtering: "YES"

## use chunks for blasting?
## coreutils split - is sometimes not easy to install
## defaulit is ON and allows faster runtime - if problems occur set to OFF
chunk_usage: "ON"


## options for expansion analyses
# define the max number of additional best blast hits to include in the follow-up analyses
# tree visualizations often are more informative if we use more than an individual (H)OG
add_blast_hits: 50
