channels:
  - bioconda
  - conda-forge
  - r
  - anaconda
dependencies:
  - snakemake=6.6.0
  - fastqc =0.11.8
  - multiqc =1.7
  - trimmomatic =0.38
  - star =2.7.3a
  - samtools =1.9
  - subread =1.6.4
  - orthofinder =2.5.2
  - muscle
  - trimal =>1.4
  - pandas =1.0.1
  - diamond >=2.0.0
  - gmp
  - kallisto
  - bioconductor-genomicfeatures
  - bioconductor-rhdf5 
  - r-readr
  - bioconductor-tximport
  - bioconductor-deseq2
  - r-dplyr >=1.0
  - r-stringr
  - ucsc-fasomerecords
  - fasttree=2.1.10
  - r-base>=3.6.0
  - r-tidyverse
  - r-ggplot2
  - bioconductor-ggtree
  - bioconductor-biostrings
  - r-seqinr
  - bioconductor-biocgenerics
  - jupyter
  - r-irkernel
